### ISSUE TITLE
Word Array Appearing in Emails

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/order-delivery-date-for-woocommerce#385]
**Describe the bug**
In new order emails, instead of delivery date ": Array" is showing.

**To Reproduce**
I'm also able to replicate it at my site. 

1. Do the setup as in screenshots:

https://prnt.sc/1s9hxxw
https://prnt.sc/1s9hzr6
https://prnt.sc/1s9i0fj
https://prnt.sc/1s9i197

2. Place an order with delivery date and timeslot and see the error: https://prnt.sc/1s9hwpy

**Isolating the problem (mark completed items with an [x]):**
- [X] This bug happens with only Order Delivery Date for WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront]
- [X] I can reproduce this bug consistently using the steps above

**Additional context**
https://wordpress.org/support/topic/array-in-email-confirmation/

The issue is coming because the Delivery Date Field label is blank. But the default delivery date field label should come as it displays on order received page.

**Comment by apeksha10** [comment]
Re-opening  this issue

After the fix is applied, the Array word does not appear in the email but I found that the delivery date shows a 00:00 number instead of the delivery date

Email : https://www.screencast.com/t/twrtouh7i
Order Received page : https://www.screencast.com/t/yVH7P8J5oE
https://www.screencast.com/t/kdTL3b2iu
