### ISSUE TITLE
Locked out date is not released when a date is changed in the admin order edit page

### ISSUE THREAD

**Issue by PradeepTyche** [TycheSoftwares/order-delivery-date-for-woocommerce#478]
**Describe the bug**
Looks like a date's lockout limit is not reduced when the the date is changed in admin's order edit page

**To Reproduce**
1. Go to 'General settings' , set 'Maximum Order Deliveries per day' to 2
2. Place 2 orders any particular date, say December 1st.
3. try to place a 3rd order and you find that December 1st is locked out as 2 orders have been already placed as lockout limit for the date is reached.
4. Go to admin and find the orders placed on the date 'December 1st' and edit the order delivery date for one of the orders and change the date to any other date.
5. Go to front end and try to placed order on December 1st. The locked out date should be available as one of the orders has been moved out of it. but the date is not available, thus the error.

**Expected behavior**
Locked out date should be available for placing order if the date of one of the orders is changed.

**Comment by Chetna1510** [comment]
I'm going to reopen this as the issue is still there.

I updated the delivery date to 27th Feb from 21st Feb but it seems the delivery date didn't update meta data due to which the issue happens.

Sharing screenshot:
![image](https://github.com/TycheSoftwares/order-delivery-date-for-woocommerce/assets/15136179/8034d7a8-56c4-4388-85a8-744f7e125684)

![image](https://github.com/TycheSoftwares/order-delivery-date-for-woocommerce/assets/15136179/fe1f03f6-1e49-4370-a53f-7062e65a32f3)

**Comment by Chetna1510** [comment]
Just need to point out that the issue comes only when HPOS enabled.
